<?php

declare(strict_types=1);

// Alphabets for the Cyrillic script.
// Generated by tools/generate-data.php - do not edit by hand.

return [
    'bul' => 'абвгдежзийклмнопрстуфхцчшщъьюя',
    'rus' => 'абвгдежзийклмнопрстуфхцчшщъыьэюяё',
    'ukr' => 'абвгдежзийклмнопрстуфхцчшщьюяєіїґ',
    'bel' => 'абвгдежзйклмнопрстуфхцчшыьэюяёіў',
    'srp' => 'абвгдежзиклмнопрстуфхцчшђјљњћџ',
    'mkd' => 'абвгдежзиклмнопрстуфхцчшѓѕјљњќџ',
];
