<?php

declare(strict_types=1);

// Alphabets for the Latin script.
// Generated by tools/generate-data.php - do not edit by hand.

return [
    'afr' => 'abcdefghijklmnopqrstuvwxyzáèéêëíîïóôúû',
    'aka' => 'abdefghiklmnoprstuwyɔɛ',
    'aze' => 'abcdefghijklmnopqrstuvxyzçöüğışə̇',
    'cat' => 'abcdefghijklmnopqrstuvwxyz·àçèéíïòóúü',
    'ces' => 'abcdefghijklmnopqrstuvwxyzáéíóúýčďěňřšťůž',
    'cym' => 'abcdefghijklmnopqrstuvwxyzàáâäèéêëìíîïòóôöùúûüýÿŵŷẁẃẅỳ',
    'dan' => 'abcdefghijklmnopqrstuvwxyzåæø',
    'deu' => 'abcdefghijklmnopqrstuvwxyzßäöü',
    'eng' => 'abcdefghijklmnopqrstuvwxyz',
    'epo' => 'abcdefghijklmnoprstuvzĉĝĥĵŝŭ',
    'est' => 'abcdefghijklmnopqrstuvwxyzäõöü',
    'fin' => 'abcdefghijklmnopqrstuvwxyzäöšž',
    'fra' => 'abcdefghijklmnopqrstuvwxyzàâçèéêëîïôùûüÿœ',
    'hrv' => 'abcdefghijklmnopqrstuvwxyzćčđšž',
    'hun' => 'abcdefghijklmnopqrstuvwxyzáéíóöúüőű',
    'ind' => 'abcdefghijklmnopqrstuvwxyz',
    'ita' => 'abcdefghijklmnopqrstuvwxyzàèéìòù',
    'jav' => 'abcdefghijklmnopqrstuvwxyzèé',
    'lat' => 'abcdefghijklmnopqrstuvwxyz',
    'lav' => 'abcdefghijklmnopqrstuvwxyzāčēģīķļņōŗšūž',
    'lit' => 'abcdefghijklmnopqrstuvwxyząčėęįšūųž',
    'nld' => 'abcdefghijklmnopqrstuvwxyzàèéëïĳ',
    'nob' => 'abcdefghijklmnopqrstuvwxyzåæø',
    'pol' => 'abcdefghijklmnopqrstuvwxyzóąćęłńśźż',
    'por' => 'abcdefghijklmnopqrstuvwxyzàáâãçéêíóôõú',
    'ron' => 'abcdefghijklmnopqrstuvwxyzâîăşţ',
    'slk' => 'abcdefghijklmnopqrstuvwxyzáäéíóôúýčďĺľňŕšťž',
    'slv' => 'abcdefghijklmnopqrstuvwxyzčšž',
    'sna' => 'abcdefghijklmnopqrstuvwxyz',
    'spa' => 'abcdefghijklmnopqrstuvwxyz¡¿áéíñóúü',
    'swe' => 'abcdefghijklmnopqrstuvwxyzäåö',
    'tgl' => 'abcdefghijklmnopqrstuvwxyzáéíñóú',
    'tuk' => 'abdefghijklmnoprstuwyzäçöüýňşž',
    'tur' => 'abcdefghijklmnopqrstuvwxyzçöüğış̇',
    'uzb' => 'abcdefghijklmnopqrstuvxyzʻ',
    'vie' => 'abcdefghijklmnopqrstuvwxyzàáâãèéêìíòóôõùúýăđĩũơưạảấầẩẫậắằẳẵặẹẻẽếềểễệỉịọỏốồổỗộớờởỡợụủứừửữựỳỵỷỹ',
    'zul' => 'abcdefghijklmnopqrstuvwxyz',
];
