<?php

declare(strict_types=1);

/**
 * Regenerates the trigram profile and alphabet data files from the whatlang-rs
 * Rust sources.
 *
 * Usage: php tools/generate-data.php [path-to-whatlang-rs]
 */
$rustRoot = $argv[1] ?? dirname(__DIR__).'/../whatlang-rs';

if (! is_dir($rustRoot.'/src/trigrams')) {
    fwrite(STDERR, "Cannot find whatlang-rs sources at {$rustRoot}\n");
    exit(1);
}

$resources = dirname(__DIR__).'/resources';

@mkdir($resources.'/trigrams', 0777, true);
@mkdir($resources.'/alphabets', 0777, true);

/**
 * Turns a Rust char literal body into the character it denotes.
 */
function rustChar(string $literal): string
{
    return match ($literal) {
        "\\'" => "'",
        '\\\\' => '\\',
        '\\n' => "\n",
        '\\t' => "\t",
        default => $literal,
    };
}

function export(string $path, string $value, string $note): void
{
    $php = "<?php\n\ndeclare(strict_types=1);\n\n// {$note}\n// Generated by tools/generate-data.php - do not edit by hand.\n\nreturn {$value};\n";

    file_put_contents($path, $php);

    printf("%-46s %8d bytes\n", substr($path, strrpos($path, 'resources')), strlen($php));
}

// ---------------------------------------------------------------------------
// Trigram profiles
// ---------------------------------------------------------------------------

$profiles = file_get_contents($rustRoot.'/src/trigrams/profiles.rs');

$blocks = [
    'latin' => 'LATIN_LANGS',
    'cyrillic' => 'CYRILLIC_LANGS',
    'arabic' => 'ARABIC_LANGS',
    'devanagari' => 'DEVANAGARI_LANGS',
    'hebrew' => 'HEBREW_LANGS',
];

// Slice the file into the per-script blocks first, so language entries are
// attributed to the right script.
$offsets = [];
foreach ($blocks as $script => $constant) {
    $pos = strpos($profiles, "pub static {$constant}:");

    if ($pos === false) {
        fwrite(STDERR, "Missing {$constant} in profiles.rs\n");
        exit(1);
    }

    $offsets[$script] = $pos;
}

$sorted = $offsets;
asort($sorted);
$starts = array_keys($sorted);
$total = 0;

foreach ($sorted as $script => $start) {
    $index = array_search($script, $starts, true);
    $end = isset($starts[$index + 1]) ? $sorted[$starts[$index + 1]] : strlen($profiles);
    $chunk = substr($profiles, $start, $end - $start);

    // Each language entry looks like: ( Lang::Spa, &[ Trigram('a', 'b', 'c'), ... ], )
    preg_match_all('/Lang::(\w+)\s*,\s*&\[(.*?)\]/s', $chunk, $entries, PREG_SET_ORDER);

    $langs = [];

    foreach ($entries as [, $lang, $body]) {
        preg_match_all("/Trigram\(\s*'(\\\\.|[^'])'\s*,\s*'(\\\\.|[^'])'\s*,\s*'(\\\\.|[^'])'\s*\)/u", $body, $trigrams, PREG_SET_ORDER);

        $list = [];

        foreach ($trigrams as [, $a, $b, $c]) {
            $list[] = rustChar($a).rustChar($b).rustChar($c);
        }

        if ($list === []) {
            fwrite(STDERR, "No trigrams parsed for Lang::{$lang}\n");
            exit(1);
        }

        $langs[strtolower($lang)] = $list;
        $total += count($list);
    }

    $php = "[\n";

    foreach ($langs as $code => $list) {
        $php .= "    '{$code}' => [\n";

        foreach (array_chunk($list, 6) as $row) {
            $php .= '        '.implode(', ', array_map(
                static fn (string $t): string => var_export($t, true),
                $row
            )).",\n";
        }

        $php .= "    ],\n";
    }

    $php .= ']';

    export(
        $resources."/trigrams/{$script}.php",
        $php,
        'Trigram profiles for the '.ucfirst($script).' script, ordered by frequency rank.'
    );
}

echo "parsed {$total} trigrams\n";

// ---------------------------------------------------------------------------
// Alphabets
// ---------------------------------------------------------------------------

foreach (['latin', 'cyrillic'] as $script) {
    $source = file_get_contents($rustRoot."/src/alphabets/{$script}.rs");

    // const DEU: &str = "abc...";  (the literal may wrap onto the next line)
    preg_match_all('/const (\w+): &str =\s*"([^"]*)"/su', $source, $consts, PREG_SET_ORDER);

    $byName = [];
    foreach ($consts as [, $name, $value]) {
        $byName[$name] = $value;
    }

    // The ordered (Lang::Xxx, CONST) table decides which consts are in use.
    preg_match_all('/\(Lang::(\w+),\s*(\w+)\)/', $source, $pairs, PREG_SET_ORDER);

    $alphabets = [];
    foreach ($pairs as [, $lang, $const]) {
        if (! isset($byName[$const])) {
            fwrite(STDERR, "Unknown alphabet const {$const}\n");
            exit(1);
        }

        $alphabets[strtolower($lang)] = $byName[$const];
    }

    $php = "[\n";
    foreach ($alphabets as $code => $chars) {
        $php .= "    '{$code}' => ".var_export($chars, true).",\n";
    }
    $php .= ']';

    export(
        $resources."/alphabets/{$script}.php",
        $php,
        'Alphabets for the '.ucfirst($script).' script.'
    );
}
